services:
  projectmanagement.api:
    image: ${DOCKER_REGISTRY-}projectmanagementapi
    build:
      context: .
      dockerfile: ProjectManagement/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080;https://0.0.0.0:8081
      - ConnectionStrings__ProjectManagementDatabase=Server=projectmanagement.database;Database=Project-Management;User Id=sa;Password=projectmanagement@123;TrustServerCertificate=True;
    depends_on:
      - projectmanagement.database
 
  projectmanagement.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=projectmanagement@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: